### ISSUE TITLE
New Scraper: Madera City Council

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-fresno#27]
Create a new scraper for Madera City Council 

Jurisdiction: Madera
Website: https://www.madera.gov/home/departments/city-clerk/city-council-agendas-meetings/#tr-2022-meetings-4850011

**Comment by haileyhoyat** [comment]
@jpt-c 
correct me if i'm wrong, i think madera city council is already merged?
https://github.com/City-Bureau/city-scrapers-fresno/blob/main/city_scrapers/spiders/fre_madera_city_council.py

**Comment by jpt-c** [comment]
Looking into this one, definitely already merged- no errors in the CI job, and nothing in the feed.

**Comment by jpt-c** [comment]
Found the issue, resolved in above commit.
