### ISSUE TITLE
New Scraper: Tulare County Board of Supervisors

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-fresno#29]
Create a new scraper for Tulare County Board of Supervisors 

Jurisdiction: Tulare County
Website: https://tularecounty.ca.gov/board/board-meetings/

**Comment by jpt-c** [comment]
Image PDF: https://tularecounty.ca.gov/sites/board/assets/2022%20BOS%20Calendar.pdf

**Comment by haileyhoyat** [comment]
hi, saw your message in Slack about i think it was this pdf calendar. so do we not make a scraper for this?

**Comment by jpt-c** [comment]
Generally I wouldn't think so, If you hit others like this let me know.

**Comment by haileyhoyat** [comment]
@jpt-c roger that, thanks so much.
