### ISSUE TITLE
New Scraper: Lindsay City Council

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-fresno#37]
Create a new scraper for Lindsay City Council 

Jurisdiction: Lindsay
Website: https://www.lindsay.ca.us/meetings?field_microsite_tid_1=27

**Comment by haileyhoyat** [comment]
@jpt-c 
when fetching this url, getting this scrapy error.
also, fwiw, i get the same error when fetching the homepage as well (https://www.lindsay.ca.us/). a surface level google search points me to issues concerning encryption support for SSL and TLS. 

<img width="1402" alt="Screen Shot 2022-08-15 at 2 12 03 PM" src="https://user-images.githubusercontent.com/25486536/184691717-c88b0596-d196-4e98-b5f2-0aa628ba251a.png">
