### ISSUE TITLE
New Scraper: Woodlake City Council

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-fresno#38]
Create a new scraper for Woodlake City Council 

Jurisdiction: Woodlake
Website: https://cityofwoodlake.com/government/

**Comment by haileyhoyat** [comment]
aloha. @jpt-c 

OK, in the scrapy shell when fetching the url, im getting the below error. 
(i know the url looks weird. the website uses an iframe of agenda pdfs stored in a google drive folder, and the url is the iframe url)

        >>> fetch('https://drive.google.com/embeddedfolderview?id=1BlNtMxhYJTbrjeqGQUkZhj_8RtqrX1eI#list')
        2022-09-28 23:24:57 [scrapy.downloadermiddlewares.robotstxt] DEBUG: Forbidden by robots.txt: <GET https://drive.google.com/embeddedfolderview?id=1BlNtMxhYJTbrjeqGQUkZhj_8RtqrX1eI#list>
        >>>

**Comment by jpt-c** [comment]
Hey, just replied on Slack too :)

Don't try to scrape Google Drive, easy way to get blocked by Google altogether which is no fun.

If that's the source for their agenda we'll need people to handle this in a different way.  Let's leave this one be.

**Comment by haileyhoyat** [comment]
using google drive to store their agendas instead of displaying the agendas directly on their website. can’t scrape google drive (they block very fast, and it could affect your home use of google).
