### ISSUE TITLE
New Scraper: Kings County Board of Supervisors

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-fresno#39]
Create a new scraper for Kings County Board of Supervisors 

Jurisdiction: Kings County
Website: https://www.countyofkings.com/departments/board-of-supervisors/calendar-agendas-and-summaries

**Comment by haileyhoyat** [comment]
@jpt-c 
hey, OK so i found this calendar on their website. my question is what's the easiest way to scrape this thing? is this a wordpress calendar thing?
https://www.countyofkings.com/community/calendar-of-events

**Comment by jpt-c** [comment]
Tribe calendars have an endpoint like wp-json/tribe/events/v1/events which I'm not seeing on this page.

Here's an example of one of those: https://github.com/City-Bureau/city-scrapers-atl/blob/main/city_scrapers/spiders/atl_regional_commission.py

I haven't done exhaustive check, but this may just be a normal scrape needed.
