### ISSUE TITLE
New Scraper: Friant Water Authority

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-fresno#44]
Create a new scraper for Friant Water Authority 

Jurisdiction: 
Website: https://friantwater.org/calendar

**Comment by RenTrieu** [comment]
Hello, may I work on this task?

**Comment by jamesturk** [comment]
Hi Darren, yes, thank you again!

**Comment by haileyhoyat** [comment]
@RenTrieu Hi Darren. My name is Hails. Thank you so much for helping out on the repo, we really appreciate it. 

i know a lot of the issues are assigned to me; if you find an issue you want to work on, even if it's assigned, by all means comment on it and i'll reassign it to you instead. thanks again, cheers.
